### PR TITLE
Write & Read Duplicate Inine Schemas Correctly

### PR DESCRIPTION
**Pull request by andrewaustin**
If a user defined record is repeated within a schema it is only inlined
once. The second reference to that type is simply specified by name. Before
this change, the name would not be written out or parsed correctly
because the code did not properly handle (de)-serialization of
RecordReferenceSchemas.

This change includes tests confirming the desired behavior.

### CODE REVIEW

**Comment by andrewaustin** [comment]
@mdlavin @xdumaine I guess you're the ones that should review this one.

**Comment by mdlavin** [comment]
It looks like you added fixes for both the reading and writing side, but there are only new testcases for the reader.  Is it possible to write tests for the writer too?

**Comment by andrewaustin** [comment]
Updated to include test for the writer.

**Comment by andrewaustin** [comment]
@xdumaine Any thoughts?

**Comment by xdumaine** [comment]
It looks good to me. I would prefer using `instanceof` to constructor name
but I'm not sure where RecordReference is defined.

**Pull request merged**
