### PR TITLE
Be consistent in semi-colon usage and general cleanup.

### PR DESCRIPTION
**Pull request by andrewaustin**
If we're going to be maintaining this module, might as well clean up some minor things.

### CODE REVIEW

**Comment by andrewaustin** [comment]
@mdlavin @xdumaine I guess you're the ones that should review this one.

**Comment by mdlavin** [comment]
I'm ok with the change.  Did you use a tool to find these issues?  If so, can you contribute the config for the linter too so that it doesn't regress?

**Comment by andrewaustin** [comment]
I used webstorm built in linter for most of the things. I would love to add ```jscs``` to the project that run part of the unit tests, but I think if we start going down that route we have to commit to using our fork over upstream.

**Comment by mdlavin** [comment]
It feels like this change is already a commitment to use our fork.  If this
is just a branch, then you can submit this PR to upstream and merge it in
the normal flow.  It's not needed for our immediate use.  If we are
committed to maintaining it long term, then this sort of style cleanup
makes sense.

**Comment by andrewaustin** [comment]
Upstream is dead as far as I can tell.

**Comment by mdlavin** [comment]
I agree, if we care about style enough to make these changes, let's enforce
it with a linter

**Comment by andrewaustin** [comment]
It's my intention to rebase this change on master instead of Xander's branch.

**Pull request closed without merging**
