### PR TITLE
Allow dependent schemas to be referenced multiple times.

### PR DESCRIPTION
**Pull request by andrewaustin**
Before this change any type defined within the schema could not be
referenced. Add any defined records to the list of schemas so we can
look them up later.

### CODE REVIEW

**Comment by xdumaine** [comment]
LGTM

**Comment by mdlavin** [comment]
Can you add a testcase so that it continues to work in the future?

**Comment by andrewaustin** [comment]
I'm not sure we actually need this anymore. If I decide we do I'll add tests, otherwise I'll close this.

**Comment by andrewaustin** [comment]
Closing since we don't need this.

**Pull request closed without merging**
